### ISSUE TITLE
Why this error on start the bot?

### ISSUE THREAD

**Issue by thenewgessiko** [0Supa/pepega-tts#37]
Why this error on start the bot?
![Immagine 2022-06-11 140051](https://user-images.githubusercontent.com/79633910/173187042-d5716336-7d1d-4ebe-887f-b07fde2203ab.png)
?

**Comment by Julia-Roman** [comment]
What node version are you running?

**Comment by thenewgessiko** [comment]
NodeJS in replit website.

Il Sab 11 Giu 2022, 17:40 Supa ***@***.***> ha scritto:

**Comment by Julia-Roman** [comment]
You'll need to use a newer node version that supports the optional chaining operator (`?.`), or make a fork and adjust the code yourself.

**Comment by thenewgessiko** [comment]
So if I update the replit nodejs is it possible that it works correctly?

Il Sab 11 Giu 2022, 19:33 Supa ***@***.***> ha scritto:
